<div class="limiter">
    <div class="container-login100 shadow">
        <div class="card p-5 m5">
        <span class="login100-form-title">
                <img src="/img/logo.png" alt="" style="width: 150px; right: 100px;"> 
                <h4>Login</h4>      
        </span>
            <form method="post" action="/autenticar" class="login100-form validate-form">
                <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                    <input class="input100" type="text" name="login" placeholder="Username">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-user" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="Password is required">
                    <input class="input100" type="password" name="senha" placeholder="Senha">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Entrar
                    </button>
                    <?php if ($this->view->login == 'erro') { ?>
                        <div class="row">
                            <div class="col">
                                <span class="text text-danger">*Login ou senha inválido(s)</span>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $('.js-tilt').tilt({
        scale: 1.1
    })
</script>