<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../../production/images/favicon.ico" type="image/ico" />

    <title>App | Controller </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="index/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="index/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="index/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="index/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="index/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="index/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="index/css/util.css">
    <link rel="stylesheet" type="text/css" href="index/css/main.css">
    <!--===============================================================================================-->
    </hrad>



<body class="nav-md">
    <div class="container body">
        <?= $this->content() ?>
    </div>

    <!--===============================================================================================-->
    <script src="index/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="index/vendor/bootstrap/js/popper.js"></script>
    <script src="index/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="index/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="index/vendor/tilt/tilt.jquery.min.js"></script>

    <!--===============================================================================================-->
    <script src="index/js/main.js"></script>

</body>

</html>